MidUpVcode/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from MidUpVcode import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^myapp/', include('Myapp.urls',namespace='myapp')),
]

Myapp/urls.py
from django.conf.urls import url

from Myapp import views

urlpatterns = [
    url(r'^register/',views.register,name='register' ),
    url(r'^login/',views.login,name='login' ),
    url(r'^logout/',views.logout,name='logout' ),
    url(r'^mine/',views.mine,name='mine' ),
    url(r'^fuli/',views.fuli,name='fuli' ),
    url(r'^lottery/',views.lottery,name='lottery' ),
    url(r'^fuckoff/',views.fuckoff,name='fuckoff' ),


    url(r'^getvcode',views.getvcode,name='getvcode' ),

]

Myapp/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    uname=models.CharField(max_length=20,unique=True)
    upwd=models.CharField(max_length=20)

    #用于关联用户上传的头像图片
    uicon=models.ImageField(null=True,blank=True,default=None)

MidUpVcode/views.py
from django.shortcuts import render


def index(request):
    return render(request,'index.html')

Myapp/views.py
import os

import io
import random
import string

from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from MidUpVcode.settings import BASE_DIR, MEDIA_ROOT, STATIC_URL
from Myapp.models import User


def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        uname = request.POST.get('uname', None)
        upwd = request.POST.get('upwd', None)

        #获取用户输入的验证码
        vcode = request.POST.get('vcode', None)

        #拿到用户上传的文件数据，类型是框架类InMemoryUploadedFile
        uiconFile = request.FILES.get('uicon', None)

        # <class 'django.core.files.uploadedfile.InMemoryUploadedFile'>
        print(uname, upwd, vcode, uiconFile, type(uiconFile))
        # f=InMemoryUploadedFile()

        # 手动存储上传的文件、
        #自定义文件位置
        fp = os.path.join(MEDIA_ROOT, 'x-' + uiconFile.name)

        #写入文件
        with open(fp, 'wb')as file:

            #逐'桶'读取上传的文件数据，并写入本地文件
            for buffer in uiconFile.chunks():
                file.write(buffer)

        # 校验验证码
        # 从session中获取正确的验证码
        sessVcode = request.session.get('vcode', None)

        # 比较用户输入的验证码与正确的验证码是否匹配
        #事先全部转换为大小写，这样用户可以忽略大小写
        if vcode and sessVcode and vcode.lower() == sessVcode.lower():

            user = User()
            user.uname = uname
            user.upwd = upwd

            #将上传过来的文件直接赋值给用户的ImageField字段uicon
            #框架会自动将图片存储在MEDIA_ROOT中
            if uiconFile:
                user.uicon = uiconFile
                user.save()

            return HttpResponse('注册成功')
        else:
            return HttpResponse('注册失败')


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        uname = request.POST.get('uname', None)
        upwd = request.POST.get('upwd', None)
        vcode = request.POST.get('vcode', None)

        # 校验验证码
        sessVcode = request.session.get('vcode', None)
        if vcode and sessVcode and vcode.lower() == sessVcode.lower():
            user = User.objects.filter(uname=uname).first()
            if user and upwd == user.upwd:
                request.session['uname'] = user.uname
                request.session['uicon'] = user.uicon.name

                return redirect(reverse('myapp:mine'))
            else:
                return HttpResponse('登录失败')
        else:
            return HttpResponse('登录失败')


def logout(request):
    return None


def mine(request):
    uname = request.session.get('uname', None)
    uicon = request.session.get('uicon', None)
    if uname:
        data = {
            'uname': uname,
            'uiconpath': STATIC_URL + 'uploads/' + uicon,
            'uiconfp': 'uploads/' + uicon,
        }
        return render(request, 'mine.html', context=data)
    else:
        return redirect(reverse('myapp:login'))


def fuli(request):
    print(5 / 0)
    return render(request, 'fuli.html', context={'imgpath': 'dj.jpg'})


def lottery(request):
    return None


def fuckoff(request):
    return None


'''
生成并返回验证码
'''


def getvcode(request):
    # 随机生成验证码
    # 设置生成大小写字母加数字的属性
    population = string.ascii_letters + string.digits
    # 随机生成4个大小写字母加数字
    letterlist = random.sample(population, 4)
    # 将生成的列表[a,A,1,2]用空字符''连接成字符串(aA12)
    vcode = ''.join(letterlist)

    # 保存该用户的验证码
    request.session['vcode'] = vcode

    # 绘制验证码
    # 创建画布（'RGB'格式，（宽157，高50），随机颜色）
    image = Image.new('RGB', (157, 50), color=getRandomColor())
    # 创建画布的画笔
    draw = ImageDraw.Draw(image)
    # 绘制文字
    # 设置字体样式的路径
    path = os.path.join(BASE_DIR, 'static', 'fonts', 'ADOBEARABIC-BOLDITALIC.OTF')
    # 设置字体样式
    font = ImageFont.truetype(font=path, size=40)

    # 根据生成的字符串长度遍历字符串的每个字符
    for i in range(len(vcode)):
        # 绘制文字（设置开始的位置（xy）,字符串的每个字符，颜色，字体样式）
        draw.text((20 + 30 * i, 5), vcode[i], fill=getRandomColor(), font=font)

    # 添加噪声
    # 设置噪点的最大个数
    for i in range(200):
        # 设置噪点的位子（xy）
        position = (random.randint(0, 157), random.randint(0, 50))
        # 画噪点（位置（xy）,颜色）
        draw.point(position, fill=getRandomColor())

    # 返回验证码
    # 删除画笔
    del draw
    # 创建字节容器
    buffer = io.BytesIO()
    # 将画布内容丢入容器,保存画布到容器中，设置格式为'png'
    image.save(buffer, 'png')
    # 返回容器内的字节,内容为容器中值，类型为图片/png格式
    return HttpResponse(content=buffer.getvalue(), content_type='image/png')


# 创建随机生成的颜色（'RGB'）
def getRandomColor():
    red = random.randint(0, 255)
    green = random.randint(0, 255)
    blue = random.randint(0, 255)
    return (red, green, blue)

templates/fuckoff.html
{#黑名单用户访问任何路由都返回当前页面#}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FUCK OFF</title>
</head>
<body>
<h1>您好，请这么滚==></h1>
</body>
</html>

templates/fuli.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>福利请笑纳</title>
</head>
<body>
<h3>一下是福利请笑纳</h3>
<img src="{% static imgpath %}" alt="">
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>老狼请吃鸡</title>
</head>
<body>
<h3>欢迎访问老狼吃鸡网站</h3>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript">
{#        创建鼠标点击验证码事件#}
        $(function () {
{#            创建id为vcode的鼠标点击时间#}
            $('#vcode').click(function () {
{#                    当点击这个标签时，其属性src会自动生成数字添加到后缀中，以此来重新生成新的验证码#}
                    $(this).attr('src','/myapp/getvcode'+Math.random())
            })
        })
    </script>


</head>
<body>
<form action="{% url 'myapp:login' %}" method="post">
    {% csrf_token %}
    <input type="text" placeholder="请输入用户名" name="uname"><br>
    <input type="password" placeholder="请输入用户密码" name="upwd"><br>
    

    <img src="/myapp/getvcode/" id="vcode"><br>
    <input type="text" placeholder="请输入验证码" name="vcode"><br>
    <input type="submit" value="登录"><br>
</form>
</body>
</html>

templates/mine.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
</head>
<body>
<h3>老狼:欢迎你，{{ uname }},叔叔带你吃鸡</h3>
<p>↓这是网络图片</p>
<img src="{{ uiconpath }}">
<p>↓这是本地图片</p>
<img src="{% static uiconfp %}">
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript">
{#        创建鼠标点击验证码事件#}
        $(function () {
{#            创建id为vcode的鼠标点击时间#}
            $('#vcode').click(function () {
{#                    当点击这个标签时，其属性src会自动生成数字添加到后缀中，以此来重新生成新的验证码#}
                    $(this).attr('src','/myapp/getvcode'+Math.random())
            })
        })
    </script>


</head>
<body>
{#注册表单#}
{#提交表单时再次访问注册路由#}
{# enctype="multipart/form-data"支持上传 #}
<form action="{% url 'myapp:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" placeholder="请输入用户名" name="uname"><br>
    <input type="password" placeholder="请输入用户密码" name="upwd"><br>

{#    用于上传头像的表单控件#}
    <input type="file" name="uicon" style="margin:5px 0"><br>
    
    {#用于显示验证码的控件#}
    {#SRC是一个返回图片字节数据的路由#}
    {#id用于定义点击事件，看不清时重新获取验证码数据#}
    <img src="/myapp/getvcode/" id="vcode"><br>

    {#用户数据让验证码#}
    {#name='vcode'定义后台获取用户输入数据的键#}
    <input type="text" placeholder="请输入验证码" name="vcode"><br>
    <input type="submit" value="注册"><br>
</form>
</body>
</html>